config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'contact', to: 'contact#index'
  resource :contact_message,
           only: :create,
           as: 'contact',
           path: 'contact',
           controller: 'contact'

  get 'about', to: 'home#about'

  resources :users, only: %i[index show]
  resources :posts

  root 'home#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base application controller class.
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: exception.message }
      format.json { render nothing: true, status: :forbidden }
      format.js { head :forbidden, content_type: 'text/html' }
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Contains application-level helpers.
module ApplicationHelper
  def active_link_to(*args, &block)
    index = block_given? ? 1 : 2
    args[index] ||= {}
    args[index][:class_active] ||= 'is-active'
    super(*args, &block)
  end

  def title(text)
    content_for(:title, " - #{text}")
  end

  def body_classes(*classes)
    content_for :body_classes, classes.join(' ')
  end

  def vertical_form_for(object, *args, &block)
    simple_form_for object, *args, &block
  end

  def horizontal_form_for(object, *args, &block)
    options = args.extract_options!
    horizontal_opts = {
      wrapper: :horizontal,
      wrapper_mappings: {
        boolean: :horizontal_checkbox,
        radio_buttons: :horizontal_radio_buttons,
        select: :horizontal_select
      }
    }
    merged = options.merge horizontal_opts
    simple_form_for object, *(args << merged), &block
  end

  def markdown(text)
    Sharparam::Markdown.render(text)
  end
end

app/views/application/_flash_notifications.html.slim
- return if flash.empty?
- flash.delete(:timedout)

section.notifications
  .container
    - flash.each do |key, value|
      .notification class="is-#{key}"
        button.delete
        = value

app/views/application/_footer.html.slim
footer.footer
  .content.has-text-centered
    p
      = t :copyright
      =<> link_to 'This site is open source', 'https://github.com/Sharparam/sharparam.com'
      | and licensed under the
      =< link_to 'MPL 2.0 license', 'https://www.mozilla.org/en-US/MPL/2.0/'
      | . The website content is licensed under a
      =< link_to 'CC-BY-NC-ND license', 'https://creativecommons.org/licenses/by-nc-nd/4.0/'
      | .
    p
      = link_to 'https://creativecommons.org/licenses/by-nc-nd/4.0/', title: 'CC-BY-NC-ND' do
        span.icon.is-large: i.fab.fa-creative-commons.fa-2x
        span.icon.is-large: i.fab.fa-creative-commons-by.fa-2x
        span.icon.is-large: i.fab.fa-creative-commons-nc.fa-2x
        span.icon.is-large: i.fab.fa-creative-commons-nd.fa-2x

app/views/application/_navbar.html.slim
nav.navbar class="#{local_assigns[:class] || ''}" role="navigation" aria-label="main navigation"
  .container
    .navbar-brand
      = link_to '#', root_path, class: 'navbar-item has-text-centered is-size-4'
      /= image_pack_tag 'media/application/images/logo_pan.png'
      a.navbar-burger.burger role="button" aria-label="menu" aria-expanded=false data-target="navbar"
        span aria-hidden=true
        span aria-hidden=true
        span aria-hidden=true
    #navbar.navbar-menu
      .navbar-start
        = active_link_to t('home.title'), root_path, class: 'navbar-item', active: :exclusive
        = active_link_to t('blog.title'), posts_path, class: 'navbar-item'
        = active_link_to t(:contact), contact_path, class: 'navbar-item'
        = active_link_to t(:about), about_path, class: 'navbar-item'
      .navbar-end
        - if user_signed_in?
          .navbar-item.has-dropdown.is-hoverable
            a.navbar-link
              span.icon: i.fas.fa-user
              span = current_user.username
            .navbar-dropdown
              = link_to 'Show profile', current_user, class: 'navbar-item'
              = link_to 'Edit profile', edit_user_registration_path, class: 'navbar-item'
              hr.navbar-divider
              = link_to t(:logout), destroy_user_session_path, method: :delete, class: 'navbar-item'
        - else
          = link_to t(:login), new_user_session_path, class: 'navbar-item'